### ISSUE TITLE
AP1155 Base Implementation

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/assembly-press#115]
Planning on starting this soon but putting up an issue for this. In my head this is gonna be almost exactly the same as the AP721 architecture, except that the AP1155.sol will have an additional "collect" function on it that lets ppl mint copies of existing tokens that have been created/data stored in the database. theres other mechanisms that need to be worked out that differ from 721 but will surface those when I get into the implementation

**Comment by salieflewis** [comment]
Closing due to protocol changes.
