### ISSUE TITLE
AP721 Curation/Connection Strategy Implementation

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/assembly-press#116]
Still undecided on the name of what we have been calling the "Curation" strategy will be. trying to avoid using the word curation. This will initially be a strategy that adds a data validation check that data getting stored per token in the database are Listing structs, and also come with a strategy specific metadata renderer. Logic file I have in mind will be similar to the Hybrid access logic implemented previously that comes with role based admin / manager permissions, along with an allowlist check for "user" level permissions. will try to introduce the concept of a "logic router" in this impl as well

Work for this has been done in previous branches, just needs to get ported over to the new database first arch so wont be a big lift.

Whats interesting is this is potentially separate from adding few models or other things on top of the database. still learning/thinking about how we actually plug and play different functionality on top of the core Database contract

**Comment by salieflewis** [comment]
Closing due to protocol changes.
