### ISSUE TITLE
Add "multi" functions to AP721 database implementation

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/assembly-press#118]
The new database entry point architecture enables users to interact with multiple rows in the database (individual erc721 contracts) at once. Haven't added these yet, but they are simple for loops of already existing "single target" functions. may need to re write the existing functions a bit so they leverage internal calls that can be reused in the for loops.

ex:
- multiStore(address[] memory targets, uint256[] memory quantities, bytes[] memory data)

**Comment by salieflewis** [comment]
Did this get resolved in #126?

cc: @0xTranqui

**Comment by salieflewis** [comment]
Closing due to protocol changes.
