### ISSUE TITLE
Turn AP into a monorepo

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/assembly-press#136]
Turning AP into a monorepo will set us up to eventually provide a full local testing environment, similar to things like scaffold-eth. An ideal version of this will provide the ability to spin up a foundry anvil chain that is both integrated into a front end (next?) environment with the backend indexing + caching events on this chain, and the foundry environment giving you the ability to update the protocol level of your database in real time.

First step: turn AP into a monorepo

**Comment by salieflewis** [comment]
For some reason when you mentioned this to me I thought you were just talking about #114 

I'll definitely carve out time to execute #114 before Friday. As per this other stuff, probably best to fully scope it out and implement parts over time.
