### ISSUE TITLE
Add a token key to the `AP721DatabaseV1` getAllData returns

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/assembly-press#99]
right now calling `getAllData` or returns all of the active tokenData for a given database. the problem is it doesnt tell you what tokenId this is associated with, so in cases where tokens have been burned this may be confusing. would just need to adjust the return value to add in the tokenId whose data is being returned. would make those functions much nicer for front ends

**Comment by 0xTranqui** [comment]
would also need to add back in the "does token exist check" and if not then continue into the for loop that used to be there

**Comment by salieflewis** [comment]
Closing due to protocol changes.
